#!/bin/bash
set -e

# 1. Clean previous builds
rm -rf rod-js/wasm
mkdir -p rod-js/wasm/web
mkdir -p rod-js/wasm/node

# 2. Build for Browser (ES Modules + fetch)
echo "🦀 Building for Web..."
wasm-pack build rod-wasm --target web --out-dir ../rod-js/wasm/web --release
# Remove .gitignore files generated by wasm-pack so they don't mess up npm publish
rm -f rod-js/wasm/web/.gitignore

# 3. Build for Node.js (CommonJS + fs)
echo "🦀 Building for Node.js..."
wasm-pack build rod-wasm --target nodejs --out-dir ../rod-js/wasm/node --release
rm -f rod-js/wasm/node/.gitignore

echo "✅ WASM Build Complete."