[package]
name = "rod-rs"
version = "0.1.3"
edition = "2024"
description = "A high-performance, cross-platform schema validation library powered by Rust."
license = "MIT"
repository = "https://github.com/AxiomCore/rod"
homepage = "https://rod.axiomcore.dev"
documentation = "https://rod.axiomcore.dev"
readme = "../README.md"
keywords = ["validation", "schema", "zod", "wasm", "ffi"]
categories = ["data-structures", "wasm", "parsing"]

[features]
non-thread-safe = []
macros = ["dep:rod-macros"]
default = ["macros"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
regex = "1.10"
lazy_static = "1.4"
chrono = { version = "0.4", features = ["serde"] }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
smallvec = "1.13"
rod-macros = { path = "../macros", version = "0.1.1", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
serde_json = "1.0"

[[bench]]
name = "rod_bench"
harness = false
